package com.wfd.dot1.cwfm.queries;

public interface ContractorQueryBank {
	String GET_CONTRACOTR_BY_ID="SELECT * FROM CMSCONTRACTOR WHERE CONTRACTORID = ?";
	
	String GET_ALL_WORKORDER_BY_PE_AND_CONT = "SELECT WORKORDERID, SAP_WORKORDER_NUM, CONTRACTORID, VALIDFROM, VALIDDT, UNITID,TYPEID,SECID,DEPID,STATUS FROM CMSWORKORDER WHERE CONTRACTORID = ? AND UNITID = ?";

	String GET_CONTRPEMM_BY_PE_AND_CONT="SELECT * FROM CMSCONTRPEMM WHERE CONTRACTORID = ? AND UNITID = ?";
	
    String GET_MAPPING_BY_PE_CONT = "SELECT * FROM CMSContractor_WC WHERE CONTRACTORID = ? AND UNITID = ? AND LICENCE_TYPE = ?";
}
