package com.wfd.dot1.cwfm.queries;

public interface ContractorQueryBank {
	String GET_CONTRACOTR_BY_ID="SELECT * FROM CMSCONTRACTOR WHERE CONTRACTORID = ?";
	
	String GET_ALL_WORKORDER_BY_PE_AND_CONT = "SELECT WORKORDERID, SAP_WORKORDER_NUM, CONTRACTORID, VALIDFROM, VALIDDT, UNITID,TYPEID,SECID,DEPID,STATUS FROM CMSWORKORDER WHERE CONTRACTORID = ? AND UNITID = ?";

	String GET_CONTRPEMM_BY_PE_AND_CONT="SELECT * FROM CMSCONTRPEMM WHERE CONTRACTORID = ? AND UNITID = ?";
	
    String GET_MAPPING_BY_PE_CONT = "SELECT * FROM CMSContractor_WC WHERE CONTRACTORID = ? AND UNITID = ? AND LICENCE_TYPE = ?";

    String SAVE_INSERT_CONTRACTOR_DETAILS = "INSERT INTO CMSContractorRegistration(CONTRACTORID,CONTRACTORREGID,UNITID,CODE,MANAGERNM,LOCOFWORK,TOTALSTRENGTH,MAXNOEMP,PFNUM,NATUREOFWORK,PERIODSTARTDATE,PERIODENDDATE,CONTTYPE,RCVALIDATED)\r\n"
    		+ "values((select isnull(max(CONTRACTORID),0)+1 from CMSContractorRegistration),?,?,?,?,?,?,?,?,?,?,?,?,?)";

    String GET_CONTRACTOR_DETAILS = "SELECT CONTRACTORREGID,UNITCODE,UNITNAME,CODE,CONTRACTORNAME,MANAGERNM,LOCOFWORK,SUPERVISORNAME,PFNUM,EMAILADDR,MOBILENO,ESICREGNO,CONTRACTVALIDTILL,SERVICES,CONTYPE FROM CMSContractorRegistration WHERE CONTRACTORREGID=?";

	String GET_ALL_CONTRACTORS = "SELECT CONTRACTORREGID,UNITCODE,CODE,CONTRACTORNAME,STATUS,TYPE FROM CMSContractorRegistration ";
    		
	String GET_ALL_CONTRACTOR_DETAIL_VIEW ="SELECT CONTRACTORREGID,UNITID,CODE,MANAGERNM,LOCOFWORK,TOTALSTRENGTH,MAXNOEMP,PFNUM,NATUREOFWORK,PERIODSTARTDATE,PERIODENDDATE,CONTTYPE,RCVALIDATED FROM CMSContractorRegistration where CONTRACTORREGID=?";
	
	String GET_ALL_RENEWAL_LIST_CONTRACTORS = "SELECT CONTRACTORREGID,UNITCODE,CODE,CONTRACTORNAME,STATUS FROM CMSContractorRegistration ";
	 
	String GET_ALL_CONTRACTOR_ADD_DETAIL_VIEW="SELECT ccrp.WONUMBER,cnoj.JOB_NAME,ccrp.LICENCETYPE,ccrp.WCCODE,ccrp.WCTOTAL,ccrp.WCFROMDTM,ccrp.WCTODTM,ccrp.ATTACHMENTNAME FROM CMSContractorRegPolicy ccrp "
	+ " join CMSNATURE_OF_JOB as cnoj on ccrp.NATUREOFID=cnoj.JOB_ID WHERE ccrp.CONTRACTORREGID=?";
		
	String GET_RENEWAL_CONTRACTORS_VIEW="SELECT CONTRACTORREGID,UNITCODE,UNITNAME,CONTRACTORID,CONTRACTORNAME,MANAGERNM,LOCOFWORK,SUPERVISORNAME,PFNUM,EMAILADDR,MOBILENO,ESICREGNO,CONTRACTVALIDTILL,SERVICES,CONTTYPE FROM CMSContractorRegistration where CONTRACTORREGID=?";

	String GET_RENEW_CONTRACTOR_ADD_DETAIL_VIEW="select LICENCETYPE,WCCODE,WCTOTAL,WCFROMDTM,WCTODTM,ATTACHMENTNAME,ISGLOBAL,SUBCONTAPPL from CMSContractorRegPolicy WHERE CONTRACTORREGID=?";
			
	String GET_ROLE_LIST="select UserId,FirstName,LastName,EmailId,ContactNumber,RoleName from MASTERUSER";

	String SAVE_ROLE_FORM="INSERT into MASTERUSER(FirstName,LastName,UserId,EmailId,ContactNumber,Password,RoleName)values(?,?,?,?,?,?,?)";
	

}

